server:
  ha:
    enabled: true
    raft:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = true
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://kildare-vault-0.vault.internal:8200"
          }
          retry_join {
            leader_api_addr = "https://kildare-vault-1.vault.internal:8200"
          }
          retry_join {
            leader_api_addr = "https://kildare-vault-2.vault.internal:8200"
          }
        }
        telemetry {
          prometheus_retention_time = "30m"
          disable_hostname = true
        }
